server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    platform: h2
    url: jdbc:h2:file:~/events;DB_CLOSE_DELAY=1
    username: events
    password: events
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always